export default {
  categoryId: [
    { value: '4', content: '프로젝트' },
    { value: '5', content: '스터디' },
  ],
  preferredMethod: [
    { value: '온라인', content: '온라인' },
    { value: '오프라인', content: '오프라인' },
  ],
  region: [
    { value: '해당없음', content: '선택되지 않음' },
    { value: '서울특별시', content: '서울특별시' },
    { value: '경기도', content: '경기도' },
    { value: '강원도', content: '강원도' },
    { value: '충청북도', content: '충청북도' },
    { value: '전라북도', content: '전라북도' },
    { value: '전라남도', content: '전라남도' },
    { value: '경상북도', content: '경상북도' },
    { value: '경상남도', content: '경상남도' },
    { value: '부산광역시', content: '부산광역시' },
  ],
  period: [
    { value: '1', content: '1개월' },
    { value: '2', content: '2개월' },
    { value: '3', content: '3개월' },
    { value: '4', content: '4개월' },
    { value: '5', content: '5개월' },
    { value: '6', content: '6개월' },
  ],
  contactMethod: [
    { value: '카카오톡 오픈채팅', content: '카카오톡 오픈채팅' },
    { value: '구글 폼', content: '구글 폼' },
    { value: '이메일', content: '이메일' },
  ],
  memberCount: [
    { value: '1', content: '1명' },
    { value: '2', content: '2명' },
    { value: '3', content: '3명' },
    { value: '4', content: '4명' },
    { value: '5', content: '5명' },
    { value: '6', content: '6명' },
    { value: '7', content: '7명' },
    { value: '8', content: '8명' },
    { value: '9', content: '9명' },
    { value: '10', content: '10+명' },
  ],
  skills: [
    { value: '1', content: 'Java' },
    { value: '2', content: 'Spring' },
    { value: '3', content: 'Python' },
    { value: '4', content: 'Kotlin' },
    { value: '5', content: 'Node.js' },
    { value: '9', content: 'Next.js' },
    { value: '8', content: 'React' },
    { value: '7', content: 'TypeScript' },
    { value: '11', content: 'Vue.js' },
    { value: '10', content: 'Angular' },
    { value: '12', content: 'Go' },
    { value: '13', content: 'Golang' },
  ],
};
